default: &default
  adapter: sqlite3
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mofmof_development

test:
  <<: *default
  database: mofmof_test

production:
  <<: *default
  database: mofmof_production
  username: mofmof
  password: <%= ENV['MOFMOF_DATABASE_PASSWORD'] %>
